project:
  type: website

website:
  navbar:
    logo: "gifgit.gif"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dendroica

format:
  html:
    theme:
      - cosmo
    css: styles.css

editor: visual

